[package]
name = "imaginarium"
version = "0.1.0"
edition = "2021"
license = "MIT"


[dependencies]
tiff = { version = "0.9" }
image = { version = "0.25" }
anyhow = { version = "1.0" }
bytemuck = { version = "1.21", features = ["derive"] }
num-traits = { version = "0.2" }
